export const metadata = {
  title: 'How to Read MOT History Before Buying a Used Car',
  description: 'Learn how to read MOT passes, failures, advisories and mileage history before viewing a used car in the UK.',
  alternates: { canonical: '/how-to-read-mot-history' }
};

export default function HowToReadMotHistory() {
  return <main className="article"><p className="eyebrow">USED-CAR BUYING GUIDE</p><h1>How to read MOT history before buying a used car</h1><p className="intro">MOT history is useful because it shows recorded tests over time—not just the seller’s description. It is a starting point for questions, not a substitute for inspecting the car.</p><h2>Start with the latest MOT</h2><p>Check whether the latest test passed, failed, or passed with advisories. A current advisory does not automatically make a car a bad purchase, but it gives you a specific item to inspect or ask about.</p><h2>Read the pattern, not one line in isolation</h2><p>An old failed MOT followed by a later pass often means the defect was repaired for the retest. It is still reasonable to ask what was done, especially for brakes, steering, suspension or corrosion, but it should not be treated as a current failure without evidence.</p><h2>Look for repeat advisories</h2><p>The same advisory appearing across several MOTs can suggest that maintenance has been deferred. Check whether it is still present on the latest MOT and ask for invoices or an explanation.</p><h2>Check the mileage record</h2><p>Recorded MOT mileage should generally rise over time. A drop needs an explanation; it can be a data-entry or unit issue, but it is important to verify before paying a deposit.</p><h2>What MOT history cannot tell you</h2><p>It cannot confirm current mechanical condition, service history, accident damage, stolen status, finance or insurance write-off status. Inspect the car, compare its VIN with the V5C, and arrange an independent inspection when appropriate.</p><p><a className="text-link" href="/">Run a free MOT history check →</a></p></main>;
}
